### ISSUE TITLE
ユーザライブラリの場所

### ISSUE THREAD

**Issue by hirokisince1998** [yyamnk/DataAnalysis#1]
R 4.2.0 から
C:/Users/ユーザ名/Documents/R/win-library/バージョン番号
ではなく
C:/Users/ユーザ名/Documents/AppData/Local/R/win-library/バージョン番号
に変わったようです。質問が多数ありました。

参考: https://okumuralab.org/~okumura/stat/R-win.html

**Comment by yyamnk** [comment]
情報ありがとうございます．
Rstanのインストール方法の説明に，R4.2.0の場合を追記しました．

https://github.com/yyamnk/DataAnalysis/blob/master/install_pkg/windows.md#rstan%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB
